branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '10'
- '12'
- '14'
env:
  global:
  - COVERALLS_PARALLEL=true
install:
- sudo apt update
- sudo apt -y install libpulse-dev pulseaudio
- yarn
script:
- pulseaudio --start
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
notifications:
  webhooks: https://coveralls.io/webhook
