branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '8'
before_install:
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install:
- sudo apt update
- sudo apt -y install libpulse-dev
- yarn
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
